[program:con1_action_cond_stage1]
directory=/workspace/ts_JEPA_con1_clean
command=/workspace/ts_JEPA_con1_clean/.venv/bin/python -u scripts/train.py pi05_libero_con1_action_cond_40k --exp-name=con1_action_cond_stage1_2k --checkpoint-base-dir=/workspace/artifacts/checkpoints --no-wandb-enabled --num-workers=0 --overwrite --num-train-steps=2000 --keep-period=1 --batch-size=64 --con1-lr-multiplier=2
autostart=false
autorestart=false
stopasgroup=true
killasgroup=true
stopwaitsecs=60
environment=PYTHONPATH="/workspace/ts_JEPA_con1_clean/src",CUDA_VISIBLE_DEVICES="0,1,2,3",LD_PRELOAD="/usr/lib/x86_64-linux-gnu/libnccl.so.2",HF_HOME="/workspace/.hf_home",HF_HUB_OFFLINE="1",XLA_PYTHON_CLIENT_PREALLOCATE="false",NCCL_P2P_DISABLE="1",NCCL_IB_DISABLE="1"
stdout_logfile=/workspace/artifacts/checkpoints/con1_action_cond_stage1_2k.log
stderr_logfile=/workspace/artifacts/checkpoints/con1_action_cond_stage1_2k.err.log
stdout_logfile_maxbytes=52428800
stderr_logfile_maxbytes=52428800
