[program:con1_precompute_displacement]
command=/opt/supervisor-scripts/con1-precompute-displacement.sh
process_name=%(program_name)s_%(process_num)02d
numprocs=4
environment=CUDA_VISIBLE_DEVICES="%(process_num)s",WORKER_RANK="%(process_num)s"
autostart=false
autorestart=unexpected
startsecs=5
stopasgroup=true
killasgroup=true
stdout_logfile=/workspace/artifacts/logs/con1_precompute_displacement_%(process_num)02d.log
stderr_logfile=/workspace/artifacts/logs/con1_precompute_displacement_%(process_num)02d.err.log
stdout_logfile_maxbytes=10485760
stdout_logfile_backups=2
stderr_logfile_maxbytes=10485760
stderr_logfile_backups=2
