[program:con2_offline]
command=/opt/supervisor-scripts/con2-offline.sh
numprocs=1
environment=CUDA_VISIBLE_DEVICES="0,1,2,3",XLA_PYTHON_CLIENT_PREALLOCATE="false"
autostart=false
autorestart=unexpected
startsecs=10
stopasgroup=true
killasgroup=true
stdout_logfile=/workspace/artifacts/logs/con2_offline.log
stderr_logfile=/workspace/artifacts/logs/con2_offline.err.log
stdout_logfile_maxbytes=52428800
stdout_logfile_backups=3
stderr_logfile_maxbytes=52428800
stderr_logfile_backups=3
